#home_dir - path to local cougarvision repo
home_dir: /home/johnsmith/cougarvision 
#True to send detections to consumer emails
email_alerts: True
#True to send detections to earthranger
er_alerts: True 
#detector_model - path to detector model
detector_model: /home/johnsmith/cougarvision/detector_models/megadetector_v4.1.pb 
#classifier_model - path to classifier model
classifier_model: /home/johnsmith/cougarvision/classifier_models/EfficientNetB5_456_Unfrozen_05_0.26_0.92.h5 
checkpoint_frequency: -1 
#log_dir - path to logs (must create this folder first)
log_dir: /home/johnsmith/cougarvision/logs/
#classes - path to the class list for the classifier model
classes: /home/johnsmith/cougarvision/labels/sw_classes.txt 
#Run version that allows for images cast to two screens? True/False
visualize_output: True
#for visualizing output, folder for cougarvision to put all images
path_to_unlabeled_output: /path/to/unlabeled/img/folder
#for visualizing output, folder for cougarvision detections with bounding boxes
path_to_labeled_output: /path/to/labeled/img/folder
#the emails that will receive email alerts, can be multiple emails
consumer_emails: [your@email.com]
#emails to recieve daily check-in and confidence of detections 
dev_emails: [your@email.com] 
#threshold confidence score 
confidence: 0.7
#cpu threads
threads: 8
#strike force api url
strikeforce_api: https://api.strikeforcewireless.com/api/v2/
#strikeforce wireless username 
username_scraper: yourusername.cam@gmail.com
#strikeforce wireless password
password_scraper: yourpassword
#authorization token from Strike Force
auth_token: <must get from web dev tools after strikeforcewireless login>
#save_dir - path to where the images get stored (must create folder)
save_dir: /home/johnsmith/images/ 
#dict of camera names and their respective strikeforce wireless ids, these must be retrieved from
#strikeforce wireless web dev tools in the code and currently the cam names must be 4 chars long 
camera_names: {'62201': B018, '59760': B016...}  
#animals that the detector will send alerts for if detected (from class list)
alert_targets: [cougar, bobcat, skunk, deer, dog, coyote, rabbit, elephant]
#checkn_interval - time interval between still-alive emails to let us know no errors have crashed
#cougarvision if it's running constantly
checkin_interval: 24
#x-csrf token retreived from earthranger interactive api example requests, must be logged into an
#existing earthranger account with interactive api access
token: [insert token]
#authorization bearer token retreived from same earthranger interactive api example requests 
authorization: Bearer [insert authorization]
#the time between repeating running fetch_and_alert, if visualize_output = True, it will be in seconds and if it = False it will be in minutes
run_scheduler: 10
#color of the bounding box
color: 'LawnGreen'
#color: 'Orange'
#color: 'Azure'
