detector_model: /mnt/machinelearning/megaDetector/megadetector_v4.1.pb
classifier_model: /mnt/machinelearning/Models/Southwest/EfficientNetB5_456_Unfrozen_01_0.58_0.82.h5
username: shiverctl@gmail.com
password: edgar&12345
#username: bioreserve.cam@gmail.com
#password: odtreqluyhuurmuu
from_emails: ["anayacreedence@gmail.com"]
#from_emails: ["support@bigfootsmtp.com", "noreply@wirelesstrophycam.com"]
# to_emails: ["jaredmacshane@gmail.com","tswanson@sdzwa.org", "iingram@sdzwa.org","Jesanchez@sdzwa.org","CdelaRosa@sdzwa.org"]
to_emails: ["shiverctl@gmail.com"]
#  +17142095998@tmomail.net,+4123520680@vzwpix.com
threads: 1
confidence: 0.5
