# Fetch_and_alert
home_dir:
detector_model: Path/To/MegaDetector/Model
classifier_model: Path/To/Classifier/Model
checkpoint_frequency: -1
checkpoint_path: Path/To/Checkpoint/Directory
csv_path: Path/To/SaveORLoad/CSV/File
classes: Path/To/Classifier/Classes
# Email Settings
username: Username
password: Password
from_emails: ["Email1", "Email2"]
to_emails: ["Email1", "Email2"]
confidence: 0.5
threads: 8
# Web Scraping
site: https://www.strikeforcewireless.com/login?redirect=%2Fphotos
site2: https://www.strikeforcewireless.com/photos
username_scraper: Username
password_scraper: Password
image_path: Path/To/Image/Directory
log_path: Path/To/Save/Log/File
last_id: LastIDNumber
camera_traps_path: Path/To/CameraTraps/Directory
