detector_model: /home/jaredm/Conservation_Fellowship/cougarvision/detector_models/md_v4.1.0.pb
classifier_model: /home/jaredm/Conservation_Fellowship/cougarvision/classifier_models/ig_resnext101_32x8d.pt

input_file: input_images/
output_json: output.json

crop_dir: crops/
confidence: 0.5