detector_model: /home/edgar/mnt/machinelearning/megaDetector/megadetector_v4.1.pb
classifier_model: /home/edgar/mnt/machinelearning/Models/Classification/ig_resnext101_32x8d.pt
confidence: 0.5
stream_path: rtsp://admin:NyalaChow22@localhost:8080
DEQUE_SIZE: 200
MAX_FRAME: 200
frame_size: [1024,576]
video_output_path: detected_videos
username: bioreserve.cam@gmail.com
password: ndtgidxlakzfnboj
to_emails: [testing.cougar@gmail.com, +17142095998@tmomail.net, +4123520680@vzwpix.com]
