detector_model: detector_models/md_v4.1.0.pb
classifier_model: classifier_models/ig_resnext101_32x8d.pt
confidence: 0.5
stream_path: rtsp://admin:NyalaChow22@70.95.11.101:8080
DEQUE_SIZE: 200
MAX_FRAME: 200
frame_size: [1280,720]
video_output_path: detected_videos